# Generated by Django 4.0.4 on 2022-12-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='online_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
