# Generated by Django 4.0.4 on 2022-12-24 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0002_online_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_game',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
        migrations.AddField(
            model_name='online_game',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='online_game',
            name='pc_game',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='online_game',
            name='pc_game_img',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
        migrations.AddField(
            model_name='online_game',
            name='pc_link',
            field=models.URLField(blank=True),
        ),
    ]
