# Generated by Django 4.0.4 on 2023-01-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0002_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotes',
            options={},
        ),
        migrations.AddField(
            model_name='business',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='body4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discover_article',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discover_article',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discover_article',
            name='body4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game_article',
            name='article_body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game_article',
            name='article_body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game_article',
            name='article_body4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='body4',
            field=models.TextField(blank=True),
        ),
    ]
