# Generated by Django 4.0.4 on 2022-12-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0003_online_game_image_online_game_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_reads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='blog_image')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pc_games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_game', models.CharField(max_length=200)),
                ('pc_link', models.URLField(blank=True)),
                ('pc_game_img', models.ImageField(blank=True, upload_to='blog_image')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='online_game',
            name='pc_game',
        ),
        migrations.RemoveField(
            model_name='online_game',
            name='pc_game_img',
        ),
        migrations.RemoveField(
            model_name='online_game',
            name='pc_link',
        ),
    ]
