# Generated by Django 4.0.4 on 2023-01-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0003_alter_quotes_options_business_body2_business_body3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='source_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='discover_article',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='discover_article',
            name='source_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='game_article',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='game_article',
            name='source_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sport',
            name='source_link',
            field=models.URLField(blank=True),
        ),
    ]
