# Generated by Django 4.0.4 on 2022-12-24 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0004_game_reads_pc_games_remove_online_game_pc_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_game',
            name='pc_game',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
