# Generated by Django 4.1.5 on 2023-05-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
