# Generated by Django 4.0.4 on 2022-12-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0005_online_game_pc_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game_reads',
        ),
        migrations.DeleteModel(
            name='Pc_games',
        ),
        migrations.AddField(
            model_name='online_game',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='online_game',
            name='pc_game_img',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
        migrations.AddField(
            model_name='online_game',
            name='pc_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='online_game',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='online_game',
            name='pc_game',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
