# Generated by Django 4.0.4 on 2022-12-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0006_delete_game_reads_delete_pc_games_online_game_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='online_game',
            old_name='image',
            new_name='android_game_image',
        ),
        migrations.RenameField(
            model_name='online_game',
            old_name='name',
            new_name='android_game_name',
        ),
        migrations.RenameField(
            model_name='online_game',
            old_name='link',
            new_name='android_link',
        ),
        migrations.RenameField(
            model_name='online_game',
            old_name='body',
            new_name='article_body',
        ),
        migrations.AddField(
            model_name='online_game',
            name='article_img',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
    ]
