# Generated by Django 4.0.4 on 2022-12-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0007_rename_image_online_game_android_game_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('article_body', models.TextField(blank=True)),
                ('article_img', models.ImageField(blank=True, upload_to='blog_image')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
