# Generated by Django 4.0.4 on 2022-12-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0008_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='PC_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_game', models.CharField(blank=True, max_length=200)),
                ('pc_link', models.URLField(blank=True)),
                ('pc_game_img', models.ImageField(blank=True, upload_to='blog_image')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='online_game',
            name='android_game_image',
        ),
        migrations.RemoveField(
            model_name='online_game',
            name='article_body',
        ),
        migrations.RemoveField(
            model_name='online_game',
            name='article_img',
        ),
        migrations.RemoveField(
            model_name='online_game',
            name='pc_game',
        ),
        migrations.RemoveField(
            model_name='online_game',
            name='pc_game_img',
        ),
        migrations.RemoveField(
            model_name='online_game',
            name='pc_link',
        ),
        migrations.RemoveField(
            model_name='online_game',
            name='title',
        ),
    ]
