# Generated by Django 4.0.4 on 2022-12-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0010_article_date_created_online_game_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online_game',
            name='android_game_name',
        ),
    ]
