# Generated by Django 4.0.4 on 2022-12-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0011_remove_online_game_android_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online_game',
            name='android_link',
        ),
    ]
