# Generated by Django 4.0.4 on 2022-12-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0012_remove_online_game_android_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='online_game',
        ),
    ]
