# Generated by Django 4.0.4 on 2022-12-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0013_delete_online_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='android_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='blog_image')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
