# Generated by Django 4.0.4 on 2022-12-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0014_android_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='game_article',
        ),
    ]
