# Generated by Django 4.0.4 on 2022-12-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0015_rename_article_game_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_article',
            name='article_body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game_article',
            name='article_body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game_article',
            name='article_img2',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
        migrations.AddField(
            model_name='game_article',
            name='article_img3',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
        migrations.AddField(
            model_name='game_article',
            name='title2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='game_article',
            name='title3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
