# Generated by Django 4.0.4 on 2022-12-24 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0016_game_article_article_body2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_article',
            name='date_created2',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_article',
            name='date_created3',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
