# Generated by Django 4.0.4 on 2022-12-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0017_game_article_date_created2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_article',
            name='article_body2',
        ),
        migrations.RemoveField(
            model_name='game_article',
            name='article_body3',
        ),
        migrations.RemoveField(
            model_name='game_article',
            name='article_img2',
        ),
        migrations.RemoveField(
            model_name='game_article',
            name='article_img3',
        ),
        migrations.RemoveField(
            model_name='game_article',
            name='date_created2',
        ),
        migrations.RemoveField(
            model_name='game_article',
            name='date_created3',
        ),
        migrations.RemoveField(
            model_name='game_article',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='game_article',
            name='title3',
        ),
    ]
