# Generated by Django 4.0.4 on 2022-12-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0018_remove_game_article_article_body2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='blog_image')),
                ('link', models.URLField(blank=True)),
                ('song', models.FileField(upload_to='musics/')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
