# Generated by Django 4.0.4 on 2022-12-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0019_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='link',
        ),
    ]
