# Generated by Django 4.0.4 on 2022-12-24 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0020_remove_music_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
