# Generated by Django 4.0.4 on 2022-12-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0022_did_you_know_discover_article_meme_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('football_title', models.CharField(blank=True, max_length=200)),
                ('football_body', models.TextField(blank=True)),
                ('football_img', models.ImageField(blank=True, upload_to='blog_image')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Tenis_title', models.CharField(blank=True, max_length=200)),
                ('Tenis_body', models.TextField(blank=True)),
                ('Tenis_img', models.ImageField(blank=True, upload_to='blog_image')),
                ('date_created2', models.DateTimeField(auto_now_add=True)),
                ('basketball_title', models.CharField(blank=True, max_length=200)),
                ('basketball_body', models.TextField(blank=True)),
                ('basketball_img', models.ImageField(blank=True, upload_to='blog_image')),
                ('date_created3', models.DateTimeField(auto_now_add=True)),
                ('boxing_title', models.CharField(blank=True, max_length=200)),
                ('boxing_body', models.TextField(blank=True)),
                ('boxing_img', models.ImageField(blank=True, upload_to='blog_image')),
                ('date_created4', models.DateTimeField(auto_now_add=True)),
                ('moto_title', models.CharField(blank=True, max_length=200)),
                ('moto_body', models.TextField(blank=True)),
                ('moto_img', models.ImageField(blank=True, upload_to='blog_image')),
                ('date_created5', models.DateTimeField(auto_now_add=True)),
                ('cricket_title', models.CharField(blank=True, max_length=200)),
                ('cricket_body', models.TextField(blank=True)),
                ('cricket_img', models.ImageField(blank=True, upload_to='blog_image')),
                ('date_created6', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
