# Generated by Django 4.0.4 on 2022-12-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0023_sport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport',
            old_name='Tenis_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='Tenis_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='Tenis_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='basketball_body',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='basketball_img',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='basketball_title',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='boxing_body',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='boxing_img',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='boxing_title',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='cricket_body',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='cricket_img',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='cricket_title',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='date_created2',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='date_created3',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='date_created4',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='date_created5',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='date_created6',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='football_body',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='football_img',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='football_title',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='moto_body',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='moto_img',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='moto_title',
        ),
    ]
