# Generated by Django 4.0.4 on 2022-12-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisteriaApp', '0024_rename_tenis_body_sport_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='blog_image')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
